In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import glob

In [109]:
main = pd.read_csv(r'C:\Users\danii\domclick-parser\main.csv')

In [110]:
main

,Unnamed: 0.1,Unnamed: 0,address,price,floor,0,rooms,1,2,3,...,10,kitchen,11,region,area,floors_number,build_date,complitation_year,house_material,balcony
0,0,NaN,"Краснодарский край, городской округ Город Анап...",10952600,6,NaN,2,NaN,NaN,NaN,...,NaN,23.1,NaN,anapa,46.00,8.0,empty,2024,monolith,1
1,1,NaN,"Анапа, ул Шевченко, 3",16890000,14,NaN,2,NaN,NaN,NaN,...,NaN,16.8,NaN,anapa,91.50,14.0,empty,empty,empty,2
2,2,NaN,"Краснодарский край, городской округ Город Анап...",9649380,2,NaN,1,NaN,NaN,NaN,...,NaN,18.3,NaN,anapa,41.70,8.0,empty,2024,monolith,1
3,3,NaN,"Краснодарский край, Анапский район, Анапа г., ...",8700000,8,NaN,2,NaN,NaN,NaN,...,NaN,25.0,NaN,anapa,56.00,13.0,empty,empty,monolith,0
4,4,NaN,"Краснодарский край, Анапа, Симферопольское шос...",15300000,3,NaN,2,NaN,NaN,NaN,...,NaN,empty,NaN,anapa,68.92,7.0,empty,2023,monolith,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,16191,NaN,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,8,NaN,2,NaN,NaN,NaN,...,NaN,8.6,NaN,spb,46.80,9.0,empty,2021,brick,empty
16192,16192,NaN,"Санкт-Петербург, Колпино, Загородная улица",5845050,2,NaN,1,NaN,NaN,NaN,...,NaN,16.0,NaN,spb,37.71,9.0,empty,2026,empty,empty
16193,16193,NaN,"Санкт-Петербург, Октябрьская набережная",5805466,2,NaN,1,NaN,NaN,NaN,...,NaN,16.9,NaN,spb,36.71,11.0,empty,2025,monolith,empty
16194,16194,NaN,"Санкт-Петербург, Муринская дорога",5828800,2,NaN,1,NaN,NaN,NaN,...,NaN,empty,NaN,spb,36.43,25.0,empty,2027,monolith,empty
16195,16195,NaN,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,2,NaN,2,NaN,NaN,NaN,...,NaN,6.6,NaN,spb,45.30,5.0,1962,empty,panel,0

In [111]:
main.drop(columns=['0','1','2','3','4','5','6','7', '8', '9', '10', '11', 'Unnamed: 0', 'Unnamed: 0.1'], inplace=True)

In [112]:
main

,address,price,floor,rooms,kitchen,region,area,floors_number,build_date,complitation_year,house_material,balcony
0,"Краснодарский край, городской округ Город Анап...",10952600,6,2,23.1,anapa,46.00,8.0,empty,2024,monolith,1
1,"Анапа, ул Шевченко, 3",16890000,14,2,16.8,anapa,91.50,14.0,empty,empty,empty,2
2,"Краснодарский край, городской округ Город Анап...",9649380,2,1,18.3,anapa,41.70,8.0,empty,2024,monolith,1
3,"Краснодарский край, Анапский район, Анапа г., ...",8700000,8,2,25.0,anapa,56.00,13.0,empty,empty,monolith,0
4,"Краснодарский край, Анапа, Симферопольское шос...",15300000,3,2,empty,anapa,68.92,7.0,empty,2023,monolith,empty
...,...,...,...,...,...,...,...,...,...,...,...,...
16191,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,8,2,8.6,spb,46.80,9.0,empty,2021,brick,empty
16192,"Санкт-Петербург, Колпино, Загородная улица",5845050,2,1,16.0,spb,37.71,9.0,empty,2026,empty,empty
16193,"Санкт-Петербург, Октябрьская набережная",5805466,2,1,16.9,spb,36.71,11.0,empty,2025,monolith,empty
16194,"Санкт-Петербург, Муринская дорога",5828800,2,1,empty,spb,36.43,25.0,empty,2027,monolith,empty
16195,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,2,2,6.6,spb,45.30,5.0,1962,empty,panel,0

In [2]:
main.to_csv('Ci.csv')

NameError: name 'main' is not defined

In [5]:
dk = pd.read_csv('DK.csv')

In [6]:
dk

,Unnamed: 0,address,price,floor,total_floors,rooms,square,city,remont,balcon,uid,view,year,type_perec,hot_water,fundament,kitchen
0,0,"улица Космонавтов, 47",5150000,4,5.0,1,30.0,Казань,standard,1.0,2.057140e+09,garden,1982.0,Железобетонный,0.0,Сплошной,5 м2
1,1,"улица Короленко, 93А",4400000,4,5.0,1,32.0,Казань,standard,1.0,2.057613e+09,garden,1962.0,Деревянный,0.0,Ленточный,6 м2
2,2,"Гвардейская улица, 35",3550000,10,1.0,1,18.6,Казань,standard,1.0,2.059627e+09,garden,1989.0,Железобетонный,0.0,Ленточный,"5,5 м2"
3,3,"Ново-Азинская улица, 12",5399999,4,9.0,1,27.7,Казань,standard,1.0,2.059957e+09,garden,1998.0,Железобетонный,0.0,Ленточный,"7,9 м2"
4,4,"Ново-Светлая улица, 20",6400000,8,9.0,1,33.0,Казань,standard,1.0,1.873373e+09,garden,2004.0,Железобетонный,0.0,0,"10,6 м2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38061,38061,"Параллельная улица, 9лит2",23950000,8,NaN,3,62.0,Сочи,well_done,2.0,2.058298e+09,garden,2013.0,0,0,0,20 м2
38062,38062,"улица Макаренко, 6/22",12850000,2,NaN,3,62.0,Сочи,well_done,2.0,2.058651e+09,garden,2008.0,0,0,0,0
38063,38063,"улица Войкова, 21",110000000,4,NaN,3,120.0,Сочи,well_done,2.0,2.003169e+09,garden,2012.0,Железобетонный,0,0,0
38064,38064,"улица Войкова, 21",65000000,18,NaN,3,100.0,Сочи,without_repair,2.0,2.059619e+09,garden,2012.0,Железобетонный,0,0,0
38065,38065,"улица Орджоникидзе, 17",70000000,16,NaN,3,131.0,Сочи,without_repair,2.0,2.058885e+09,garden,0.0,0,0,0,0

In [3]:
ci = pd.read_csv("Ci.csv")

In [4]:
ci

,Unnamed: 0,address,price,floor,rooms,kitchen,city,square,total_floors,year,year1,type_perec,balcon
0,0,"Краснодарский край, городской округ Город Анап...",10952600,6,2,23.1,anapa,46.00,8.0,empty,2024,monolith,1
1,1,"Анапа, ул Шевченко, 3",16890000,14,2,16.8,anapa,91.50,14.0,empty,empty,empty,2
2,2,"Краснодарский край, городской округ Город Анап...",9649380,2,1,18.3,anapa,41.70,8.0,empty,2024,monolith,1
3,3,"Краснодарский край, Анапский район, Анапа г., ...",8700000,8,2,25.0,anapa,56.00,13.0,empty,empty,monolith,0
4,4,"Краснодарский край, Анапа, Симферопольское шос...",15300000,3,2,empty,anapa,68.92,7.0,empty,2023,monolith,empty
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,16191,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,8,2,8.6,spb,46.80,9.0,empty,2021,brick,empty
16192,16192,"Санкт-Петербург, Колпино, Загородная улица",5845050,2,1,16.0,spb,37.71,9.0,empty,2026,empty,empty
16193,16193,"Санкт-Петербург, Октябрьская набережная",5805466,2,1,16.9,spb,36.71,11.0,empty,2025,monolith,empty
16194,16194,"Санкт-Петербург, Муринская дорога",5828800,2,1,empty,spb,36.43,25.0,empty,2027,monolith,empty
16195,16195,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,2,2,6.6,spb,45.30,5.0,1962,empty,panel,0

In [7]:
df = pd.concat([ci, dk])

In [10]:
df

,Unnamed: 0,address,price,floor,rooms,kitchen,city,square,total_floors,year,year1,type_perec,balcon,remont,uid,view,hot_water,fundament
0,0,"Краснодарский край, городской округ Город Анап...",10952600,6,2,23.1,anapa,46.00,8.0,empty,2024,monolith,1,NaN,NaN,NaN,NaN,NaN
1,1,"Анапа, ул Шевченко, 3",16890000,14,2,16.8,anapa,91.50,14.0,empty,empty,empty,2,NaN,NaN,NaN,NaN,NaN
2,2,"Краснодарский край, городской округ Город Анап...",9649380,2,1,18.3,anapa,41.70,8.0,empty,2024,monolith,1,NaN,NaN,NaN,NaN,NaN
3,3,"Краснодарский край, Анапский район, Анапа г., ...",8700000,8,2,25.0,anapa,56.00,13.0,empty,empty,monolith,0,NaN,NaN,NaN,NaN,NaN
4,4,"Краснодарский край, Анапа, Симферопольское шос...",15300000,3,2,empty,anapa,68.92,7.0,empty,2023,monolith,empty,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38061,38061,"Параллельная улица, 9лит2",23950000,8,3,20 м2,Сочи,62.00,NaN,2013.0,NaN,0,2.0,well_done,2.058298e+09,garden,0,0
38062,38062,"улица Макаренко, 6/22",12850000,2,3,0,Сочи,62.00,NaN,2008.0,NaN,0,2.0,well_done,2.058651e+09,garden,0,0
38063,38063,"улица Войкова, 21",110000000,4,3,0,Сочи,120.00,NaN,2012.0,NaN,Железобетонный,2.0,well_done,2.003169e+09,garden,0,0
38064,38064,"улица Войкова, 21",65000000,18,3,0,Сочи,100.00,NaN,2012.0,NaN,Железобетонный,2.0,without_repair,2.059619e+09,garden,0,0
38065,38065,"улица Орджоникидзе, 17",70000000,16,3,0,Сочи,131.00,NaN,0.0,NaN,0,2.0,without_repair,2.058885e+09,garden,0,0

In [9]:
df.to_csv("final.csv")