In [1]:
import pandas as pd
import numpy as np

In [2]:
cian_df = pd.read_csv(r'C:\Users\danii\domclick-parser\merged_data_cian.csv')

In [3]:
cian_df

,region,address,price,total_area,kitchen_area,living_area,rooms_count,floor,floors_number,build_date,...,longitude,latitude,passenger_elevator,cargo_elevator,metro,metro_distance,metro_transport,district,is_apartments,is_auction
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,14.9,2,6,8,empty,...,37.370067,44.804797,empty,empty,NaN,NaN,NaN,NaN,0,0.0
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,41.3,2,14,14,empty,...,37.305066,44.886331,1,empty,NaN,NaN,NaN,NaN,0,1.0
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,14.0,1,2,8,empty,...,37.370323,44.805473,1,empty,NaN,NaN,NaN,NaN,0,0.0
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,16.0,2,8,13,empty,...,37.330695,44.871884,1,empty,NaN,NaN,NaN,NaN,empty,1.0
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,35.4,2,3,7,empty,...,37.321874,44.929875,empty,2,NaN,NaN,NaN,NaN,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,27.6,2,8,9,empty,...,30.463626,59.756102,empty,empty,"Шушары,Купчино,Дунайская","16,17,21","transport,transport,transport","Шушары,Пушкинский",0,0.0
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,16.8,1,2,9,empty,...,30.595144,59.782357,empty,5,"Рыбацкое,Обухово,Пролетарская","17,21,21","transport,transport,transport","Колпино,Колпинский",0,0.0
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,12.8,1,2,11,empty,...,30.445292,59.901613,1,1,"Новочеркасская,Площадь Александра Невского,Ули...","5,6,7","transport,transport,transport","Невский,Невский",1,0.0
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,empty,1,2,25,empty,...,30.450474,60.037705,2,8,"Девяткино,Гражданский проспект,Академическая","5,6,11","transport,transport,transport","Полюстрово,Красногвардейский",0,0.0
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,28.0,2,2,5,1962,...,30.451595,59.863315,empty,empty,"Пролетарская,Ломоносовская,Обухово","16,3,5","walk,transport,transport","Обуховский,Невский",0,0.0

In [4]:
cian_df.columns #ЦИАН

Index(['region', 'address', 'price', 'total_area', 'kitchen_area',
       'living_area', 'rooms_count', 'floor', 'floors_number', 'build_date',
       'isСomplete', 'complitation_year', 'house_material', 'parking',
       'decoration', 'balcony', 'longitude', 'latitude', 'passenger_elevator',
       'cargo_elevator', 'metro', 'metro_distance', 'metro_transport',
       'district', 'is_apartments', 'is_auction'],
      dtype='object')

In [5]:
dk_df = pd.read_csv(r"C:\Users\danii\domclick-parser\with_metro.csv")

In [6]:
#dk_df

In [7]:
dk_df.columns #ДОМКЛИК

Index(['address', 'price', 'floor', 'total_floors', 'rooms', 'square', 'city',
       'remont', 'balcon', 'uid', 'view', 'type_perec', 'lon', 'lat',
       'metro_dist', 'metro_name'],
      dtype='object')

In [8]:
dk_cols = ['address', 'price', 'floor', 'total_floors', 'rooms', 'square', 'city',
       'remont', 'balcon', 'uid', 'type_perec', 'lon', 'lat',
       'metro_dist', 'metro_name']

cian_cols = ['region', 'address', 'price', 'total_area', 'kitchen_area',
       'rooms_count', 'floor', 'floors_number', 'build_date',
       'house_material',
       'decoration', 'balcony', 'longitude', 'latitude',
       'metro', 'metro_distance', 'metro_transport',]

In [9]:
cian_df = cian_df[cian_cols]

In [10]:
#cian_df

In [11]:
dk_df = dk_df[dk_cols]

In [12]:
rename_dk = {'address':'address', 'price':'price', 'floor':'floor', 'total_floors':'total_floors',
             'rooms':'total_rooms', 'square':'area', 'city':'city',
             'remont':'remont', 'balcon':'total_balcony', 'uid':'uid', 'type_perec':'material_type',
             'lon':'longitude', 'lat':'latitude','metro_dist':'metro_dist_km', 'metro_name':'metro_name'}

In [13]:
dk_df.rename(columns=rename_dk, inplace=True)

In [14]:
dk_df['build_date'] = None

In [15]:
dk_df

,address,price,floor,total_floors,total_rooms,area,city,remont,total_balcony,uid,material_type,longitude,latitude,metro_dist_km,metro_name,build_date
0,"Выборгская улица, 8",10680000.0,1.0,9.0,1.0,35.0,Москва,standard,1.0,2.056866e+09,brick,37.490110,55.833107,0.78,NaN,None
1,"улица Гурьянова, 9",12990000.0,3.0,12.0,1.0,40.5,Москва,standard,1.0,2.058753e+09,brick,37.721660,55.690146,0.66,NaN,None
2,"Ленинградское шоссе, 13к2",10400000.0,5.0,5.0,1.0,30.0,Москва,standard,1.0,2.056577e+09,brick,37.495419,55.819282,0.35,NaN,None
3,"Звенигородское шоссе, 3Ас1",12900000.0,3.0,9.0,1.0,32.0,Москва,standard,1.0,2.060026e+09,brick,37.556559,55.763523,0.42,NaN,None
4,"Большая Черкизовская улица, 26к2",10300000.0,5.0,5.0,1.0,31.7,Москва,standard,1.0,2.060013e+09,brick,37.737740,55.797766,0.96,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,"проспект Непокорённых, 49к2",20500000.0,7.0,16.0,4.0,135.0,Санкт-Петербург,design,2.0,1.870651e+09,brick_monolith,30.389054,59.993599,1.86,Площадь Мужества,None
30437,"Морской проспект, 33",98900000.0,2.0,7.0,4.0,241.8,Санкт-Петербург,design,2.0,1.525961e+09,brick_monolith,30.260754,59.971713,0.39,Крестовский остров,None
30438,"Ушаковская набережная, 3 к2",85000000.0,13.0,17.0,4.0,156.0,Санкт-Петербург,design,2.0,2.059036e+09,brick_monolith,30.315220,59.982272,1.07,Чёрная речка,None
30439,"Кемская улица, 14",66500000.0,2.0,7.0,4.0,124.7,Санкт-Петербург,design,2.0,1.633886e+09,brick_monolith,30.263047,59.973401,0.49,Крестовский остров,None
30440,"Парадная улица, 3к2",79000000.0,6.0,8.0,4.0,153.0,Санкт-Петербург,well_done,2.0,2.056289e+09,brick_monolith,30.367261,59.942079,1.75,Площадь Восстания,None

In [16]:
rename_cian = {'address':'address', 'price':'price', 'floor':'floor', 'floors_number':'total_floors',
             'rooms_count':'total_rooms', 'square':'area', 'region':'city',
             'decoration':'remont', 'balcony':'total_balcony', 'house_material':'material_type',
             'lon':'longitude', 'lat':'latitude','metro_distance':'metro_distance', 'metro':'metro_name',
             'build_date':'build_date', 'total_area': 'area'}

In [17]:
cian_df.rename(columns=rename_cian, inplace=True)

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\1333600021.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cian_df.rename(columns=rename_cian, inplace=True)

In [18]:
cian_df.columns

Index(['city', 'address', 'price', 'area', 'kitchen_area', 'total_rooms',
       'floor', 'total_floors', 'build_date', 'material_type', 'remont',
       'total_balcony', 'longitude', 'latitude', 'metro_name',
       'metro_distance', 'metro_transport'],
      dtype='object')

In [19]:
cian_df

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,longitude,latitude,metro_name,metro_distance,metro_transport
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,2,6,8,empty,monolith,fine,1,37.370067,44.804797,NaN,NaN,NaN
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,2,14,14,empty,empty,empty,2,37.305066,44.886331,NaN,NaN,NaN
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,1,2,8,empty,monolith,fine,1,37.370323,44.805473,NaN,NaN,NaN
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,2,8,13,empty,monolith,empty,0,37.330695,44.871884,NaN,NaN,NaN
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,2,3,7,empty,monolith,empty,empty,37.321874,44.929875,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,2,8,9,empty,brick,rough,empty,30.463626,59.756102,"Шушары,Купчино,Дунайская","16,17,21","transport,transport,transport"
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,1,2,9,empty,empty,fine,empty,30.595144,59.782357,"Рыбацкое,Обухово,Пролетарская","17,21,21","transport,transport,transport"
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,1,2,11,empty,monolith,without,empty,30.445292,59.901613,"Новочеркасская,Площадь Александра Невского,Ули...","5,6,7","transport,transport,transport"
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,1,2,25,empty,monolith,empty,empty,30.450474,60.037705,"Девяткино,Гражданский проспект,Академическая","5,6,11","transport,transport,transport"
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,2,2,5,1962,panel,empty,0,30.451595,59.863315,"Пролетарская,Ломоносовская,Обухово","16,3,5","walk,transport,transport"

In [20]:
cian_df['metro_transport'] = cian_df['metro_transport'].str.split(',').str[0]

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\3665627356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cian_df['metro_transport'] = cian_df['metro_transport'].str.split(',').str[0]

In [21]:
cian_df

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,longitude,latitude,metro_name,metro_distance,metro_transport
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,2,6,8,empty,monolith,fine,1,37.370067,44.804797,NaN,NaN,NaN
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,2,14,14,empty,empty,empty,2,37.305066,44.886331,NaN,NaN,NaN
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,1,2,8,empty,monolith,fine,1,37.370323,44.805473,NaN,NaN,NaN
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,2,8,13,empty,monolith,empty,0,37.330695,44.871884,NaN,NaN,NaN
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,2,3,7,empty,monolith,empty,empty,37.321874,44.929875,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,2,8,9,empty,brick,rough,empty,30.463626,59.756102,"Шушары,Купчино,Дунайская","16,17,21",transport
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,1,2,9,empty,empty,fine,empty,30.595144,59.782357,"Рыбацкое,Обухово,Пролетарская","17,21,21",transport
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,1,2,11,empty,monolith,without,empty,30.445292,59.901613,"Новочеркасская,Площадь Александра Невского,Ули...","5,6,7",transport
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,1,2,25,empty,monolith,empty,empty,30.450474,60.037705,"Девяткино,Гражданский проспект,Академическая","5,6,11",transport
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,2,2,5,1962,panel,empty,0,30.451595,59.863315,"Пролетарская,Ломоносовская,Обухово","16,3,5",walk

In [22]:
cian_df['metro_distance'] = cian_df['metro_distance'].str.split(',').str[0]

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\2447566494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cian_df['metro_distance'] = cian_df['metro_distance'].str.split(',').str[0]

In [23]:
cian_df['metro_name'] = cian_df['metro_name'].str.split(',').str[0]

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\179870817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cian_df['metro_name'] = cian_df['metro_name'].str.split(',').str[0]

In [24]:
cian_df = cian_df.drop(index = 5427)

In [25]:
cian_df.metro_transport.unique()

array([nan, 'transport', 'walk'], dtype=object)

In [26]:
cian_df[cian_df.metro_transport == "transport"].head(5)

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,longitude,latitude,metro_name,metro_distance,metro_transport
1227,balashikha,"Московская область, Балашиха, микрорайон Желез...",10001090,64.9,16.9,3,10,18,empty,monolith,fine,1,38.008372,55.736966,Некрасовка,9,transport
1228,balashikha,"Россия, Московская область, городской округ Ба...",6800000,43.0,7.0,2,3,9,1980,panel,empty,empty,37.968499,55.816171,Салтыковская,13,transport
1229,balashikha,"Московская область, Балашиха, микрорайон Желез...",9826960,57.2,15.5,2,17,17,empty,monolith,fine,1,38.005134,55.738902,Некрасовка,9,transport
1230,balashikha,"Московская область, Балашиха, улица Ситникова, 2",8500000,50.6,20.5,1,11,17,2018,monolith,empty,empty,37.879171,55.788884,Реутов,13,transport
1231,balashikha,"Московская область, Балашиха, микрорайон Желез...",9743125,59.5,16.4,2,2,17,empty,monolith,fine,1,38.007381,55.738838,Некрасовка,9,transport

In [27]:
d_speed = {
    "walk": 90,
    "transport": 400
}

In [28]:
cian_df["metro_speed"] = cian_df["metro_transport"].apply(lambda x: d_speed.get(x, -1))

In [29]:
cian_df

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,longitude,latitude,metro_name,metro_distance,metro_transport,metro_speed
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,2,6,8,empty,monolith,fine,1,37.370067,44.804797,NaN,NaN,NaN,-1
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,2,14,14,empty,empty,empty,2,37.305066,44.886331,NaN,NaN,NaN,-1
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,1,2,8,empty,monolith,fine,1,37.370323,44.805473,NaN,NaN,NaN,-1
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,2,8,13,empty,monolith,empty,0,37.330695,44.871884,NaN,NaN,NaN,-1
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,2,3,7,empty,monolith,empty,empty,37.321874,44.929875,NaN,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,2,8,9,empty,brick,rough,empty,30.463626,59.756102,Шушары,16,transport,400
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,1,2,9,empty,empty,fine,empty,30.595144,59.782357,Рыбацкое,17,transport,400
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,1,2,11,empty,monolith,without,empty,30.445292,59.901613,Новочеркасская,5,transport,400
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,1,2,25,empty,monolith,empty,empty,30.450474,60.037705,Девяткино,5,transport,400
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,2,2,5,1962,panel,empty,0,30.451595,59.863315,Пролетарская,16,walk,90

In [30]:
cian_df["metro_distance"] = cian_df["metro_distance"].fillna(0)

In [31]:
cian_df["metro_distance"].unique()

array([0, '9', '13', '11', '18', '17', '10', '15', '5', '19', '16', '8',
       '14', '12', '6', '4', '20', '7', '3', '30', '22', '2', '24', '21',
       '25', '1', '27', '26', '28', '23', '29', '40', '32'], dtype=object)

In [32]:
cian_df["metro_dist_km"] = cian_df["metro_speed"].astype(int) * cian_df["metro_distance"].astype(int) / 1000

In [33]:
cian_df.columns

Index(['city', 'address', 'price', 'area', 'kitchen_area', 'total_rooms',
       'floor', 'total_floors', 'build_date', 'material_type', 'remont',
       'total_balcony', 'longitude', 'latitude', 'metro_name',
       'metro_distance', 'metro_transport', 'metro_speed', 'metro_dist_km'],
      dtype='object')

In [34]:
dk_df.columns

Index(['address', 'price', 'floor', 'total_floors', 'total_rooms', 'area',
       'city', 'remont', 'total_balcony', 'uid', 'material_type', 'longitude',
       'latitude', 'metro_dist_km', 'metro_name', 'build_date'],
      dtype='object')

In [35]:
cian_df = cian_df.drop(["metro_speed", "metro_transport", "metro_distance"], axis=1)

In [36]:
cian_df.columns

Index(['city', 'address', 'price', 'area', 'kitchen_area', 'total_rooms',
       'floor', 'total_floors', 'build_date', 'material_type', 'remont',
       'total_balcony', 'longitude', 'latitude', 'metro_name',
       'metro_dist_km'],
      dtype='object')

In [37]:
cian_df = cian_df[['city', 'address', 'price', 'area', 'kitchen_area', 'total_rooms',
       'floor', 'total_floors', 'build_date', 'material_type', 'remont',
       'total_balcony', 'metro_name',
       'metro_dist_km', 'longitude', 'latitude']]

In [38]:
cian_df

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,2,6,8,empty,monolith,fine,1,NaN,0.00,37.370067,44.804797
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,2,14,14,empty,empty,empty,2,NaN,0.00,37.305066,44.886331
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,1,2,8,empty,monolith,fine,1,NaN,0.00,37.370323,44.805473
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,2,8,13,empty,monolith,empty,0,NaN,0.00,37.330695,44.871884
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,2,3,7,empty,monolith,empty,empty,NaN,0.00,37.321874,44.929875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,2,8,9,empty,brick,rough,empty,Шушары,6.40,30.463626,59.756102
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,1,2,9,empty,empty,fine,empty,Рыбацкое,6.80,30.595144,59.782357
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,1,2,11,empty,monolith,without,empty,Новочеркасская,2.00,30.445292,59.901613
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,1,2,25,empty,monolith,empty,empty,Девяткино,2.00,30.450474,60.037705
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,2,2,5,1962,panel,empty,0,Пролетарская,1.44,30.451595,59.863315

In [39]:
dk_df.columns

Index(['address', 'price', 'floor', 'total_floors', 'total_rooms', 'area',
       'city', 'remont', 'total_balcony', 'uid', 'material_type', 'longitude',
       'latitude', 'metro_dist_km', 'metro_name', 'build_date'],
      dtype='object')

In [40]:
dk_df = dk_df[['uid', 'city', 'address', 'price', 'area', 'total_rooms',
       'floor', 'total_floors', 'build_date', 'material_type', 'remont',
       'total_balcony', 'metro_name',
       'metro_dist_km', 'longitude', 'latitude']]
dk_df['kitchen_area'] = None

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\3880574541.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dk_df['kitchen_area'] = None

In [41]:
dk_df

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,None,brick,standard,1.0,NaN,0.78,37.490110,55.833107,None
1,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,None,brick,standard,1.0,NaN,0.66,37.721660,55.690146,None
2,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.35,37.495419,55.819282,None
3,2.060026e+09,Москва,"Звенигородское шоссе, 3Ас1",12900000.0,32.0,1.0,3.0,9.0,None,brick,standard,1.0,NaN,0.42,37.556559,55.763523,None
4,2.060013e+09,Москва,"Большая Черкизовская улица, 26к2",10300000.0,31.7,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.96,37.737740,55.797766,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,None,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,None
30437,1.525961e+09,Санкт-Петербург,"Морской проспект, 33",98900000.0,241.8,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.39,30.260754,59.971713,None
30438,2.059036e+09,Санкт-Петербург,"Ушаковская набережная, 3 к2",85000000.0,156.0,4.0,13.0,17.0,None,brick_monolith,design,2.0,Чёрная речка,1.07,30.315220,59.982272,None
30439,1.633886e+09,Санкт-Петербург,"Кемская улица, 14",66500000.0,124.7,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.49,30.263047,59.973401,None
30440,2.056289e+09,Санкт-Петербург,"Парадная улица, 3к2",79000000.0,153.0,4.0,6.0,8.0,None,brick_monolith,well_done,2.0,Площадь Восстания,1.75,30.367261,59.942079,None

Checkpoint

In [42]:
dk_df.to_parquet("domclick_tmp_data.parquet")
cian_df.to_parquet("cian_tmp_data.parquet")

In [43]:
dk_df

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,None,brick,standard,1.0,NaN,0.78,37.490110,55.833107,None
1,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,None,brick,standard,1.0,NaN,0.66,37.721660,55.690146,None
2,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.35,37.495419,55.819282,None
3,2.060026e+09,Москва,"Звенигородское шоссе, 3Ас1",12900000.0,32.0,1.0,3.0,9.0,None,brick,standard,1.0,NaN,0.42,37.556559,55.763523,None
4,2.060013e+09,Москва,"Большая Черкизовская улица, 26к2",10300000.0,31.7,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.96,37.737740,55.797766,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,None,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,None
30437,1.525961e+09,Санкт-Петербург,"Морской проспект, 33",98900000.0,241.8,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.39,30.260754,59.971713,None
30438,2.059036e+09,Санкт-Петербург,"Ушаковская набережная, 3 к2",85000000.0,156.0,4.0,13.0,17.0,None,brick_monolith,design,2.0,Чёрная речка,1.07,30.315220,59.982272,None
30439,1.633886e+09,Санкт-Петербург,"Кемская улица, 14",66500000.0,124.7,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.49,30.263047,59.973401,None
30440,2.056289e+09,Санкт-Петербург,"Парадная улица, 3к2",79000000.0,153.0,4.0,6.0,8.0,None,brick_monolith,well_done,2.0,Площадь Восстания,1.75,30.367261,59.942079,None

In [47]:
cian_df

,city,address,price,area,kitchen_area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude
0,anapa,"Краснодарский край, городской округ Город Анап...",10952600,46.00,23.1,2,6,8,empty,monolith,fine,1,NaN,0.00,37.370067,44.804797
1,anapa,"Анапа, ул Шевченко, 3",16890000,91.50,16.8,2,14,14,empty,empty,empty,2,NaN,0.00,37.305066,44.886331
2,anapa,"Краснодарский край, городской округ Город Анап...",9649380,41.70,18.3,1,2,8,empty,monolith,fine,1,NaN,0.00,37.370323,44.805473
3,anapa,"Краснодарский край, Анапский район, Анапа г., ...",8700000,56.00,25.0,2,8,13,empty,monolith,empty,0,NaN,0.00,37.330695,44.871884
4,anapa,"Краснодарский край, Анапа, Симферопольское шос...",15300000,68.92,empty,2,3,7,empty,monolith,empty,empty,NaN,0.00,37.321874,44.929875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16191,spb,"Санкт-Петербург, Пушкинский район, посёлок Шуш...",5791400,46.80,8.6,2,8,9,empty,brick,rough,empty,Шушары,6.40,30.463626,59.756102
16192,spb,"Санкт-Петербург, Колпино, Загородная улица",5845050,37.71,16.0,1,2,9,empty,empty,fine,empty,Рыбацкое,6.80,30.595144,59.782357
16193,spb,"Санкт-Петербург, Октябрьская набережная",5805466,36.71,16.9,1,2,11,empty,monolith,without,empty,Новочеркасская,2.00,30.445292,59.901613
16194,spb,"Санкт-Петербург, Муринская дорога",5828800,36.43,empty,1,2,25,empty,monolith,empty,empty,Девяткино,2.00,30.450474,60.037705
16195,spb,"г Санкт-Петербург, пр-кт Александровской Фермы...",5899999,45.30,6.6,2,2,5,1962,panel,empty,0,Пролетарская,1.44,30.451595,59.863315

In [57]:
dk_df["kitchen_area"] = dk_df["area"]*0.2

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\2733474051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dk_df["kitchen_area"] = dk_df["area"]*0.2

In [58]:
dk_df

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,None,brick,standard,1.0,NaN,0.78,37.490110,55.833107,7.00
1,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,None,brick,standard,1.0,NaN,0.66,37.721660,55.690146,8.10
2,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.35,37.495419,55.819282,6.00
3,2.060026e+09,Москва,"Звенигородское шоссе, 3Ас1",12900000.0,32.0,1.0,3.0,9.0,None,brick,standard,1.0,NaN,0.42,37.556559,55.763523,6.40
4,2.060013e+09,Москва,"Большая Черкизовская улица, 26к2",10300000.0,31.7,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.96,37.737740,55.797766,6.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,None,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,27.00
30437,1.525961e+09,Санкт-Петербург,"Морской проспект, 33",98900000.0,241.8,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.39,30.260754,59.971713,48.36
30438,2.059036e+09,Санкт-Петербург,"Ушаковская набережная, 3 к2",85000000.0,156.0,4.0,13.0,17.0,None,brick_monolith,design,2.0,Чёрная речка,1.07,30.315220,59.982272,31.20
30439,1.633886e+09,Санкт-Петербург,"Кемская улица, 14",66500000.0,124.7,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.49,30.263047,59.973401,24.94
30440,2.056289e+09,Санкт-Петербург,"Парадная улица, 3к2",79000000.0,153.0,4.0,6.0,8.0,None,brick_monolith,well_done,2.0,Площадь Восстания,1.75,30.367261,59.942079,30.60

In [60]:
dk_df.to_parquet("domclick_checkpoint_data.parquet")
cian_df.to_parquet("cian_checkpoint_data.parquet")

In [61]:
year_df = pd.read_csv(r"C:\Users\danii\domclick-parser\tochno_final_100_procentov_42_pro_super_max_editional.csv")

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\1413892428.py:1: DtypeWarning: Columns (11,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  year_df = pd.read_csv(r"C:\Users\danii\domclick-parser\tochno_final_100_procentov_42_pro_super_max_editional.csv")

In [90]:
years = year_df[["uid", "year"]]
years = years.dropna()
years["uid"] = years.uid.astype(float)
dk_df["uid"] = dk_df.uid.astype(float)

C:\Users\danii\AppData\Local\Temp\ipykernel_15012\575043634.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dk_df["uid"] = dk_df.uid.astype(float)

In [108]:
dk_df

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,None,brick,standard,1.0,NaN,0.78,37.490110,55.833107,7.00
1,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,None,brick,standard,1.0,NaN,0.66,37.721660,55.690146,8.10
2,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.35,37.495419,55.819282,6.00
3,2.060026e+09,Москва,"Звенигородское шоссе, 3Ас1",12900000.0,32.0,1.0,3.0,9.0,None,brick,standard,1.0,NaN,0.42,37.556559,55.763523,6.40
4,2.060013e+09,Москва,"Большая Черкизовская улица, 26к2",10300000.0,31.7,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.96,37.737740,55.797766,6.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,None,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,27.00
30437,1.525961e+09,Санкт-Петербург,"Морской проспект, 33",98900000.0,241.8,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.39,30.260754,59.971713,48.36
30438,2.059036e+09,Санкт-Петербург,"Ушаковская набережная, 3 к2",85000000.0,156.0,4.0,13.0,17.0,None,brick_monolith,design,2.0,Чёрная речка,1.07,30.315220,59.982272,31.20
30439,1.633886e+09,Санкт-Петербург,"Кемская улица, 14",66500000.0,124.7,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.49,30.263047,59.973401,24.94
30440,2.056289e+09,Санкт-Петербург,"Парадная улица, 3к2",79000000.0,153.0,4.0,6.0,8.0,None,brick_monolith,well_done,2.0,Площадь Восстания,1.75,30.367261,59.942079,30.60

In [119]:
years

                uid    year
16196  2.057140e+09  1982.0
16197  2.057613e+09  1962.0
16198  2.059627e+09  1989.0
16199  2.059957e+09  1998.0
16200  1.873373e+09  2004.0
...             ...     ...
53669  2.058298e+09  2013.0
53670  2.058651e+09  2008.0
53671  2.003169e+09  2012.0
53672  2.059619e+09  2012.0
53673  2.058885e+09     0.0

[37478 rows x 2 columns]

In [120]:
dk_df[dk_df.uid.isin(years.uid)]

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,None,brick,standard,1.0,NaN,0.78,37.490110,55.833107,7.00
1,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,None,brick,standard,1.0,NaN,0.66,37.721660,55.690146,8.10
2,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,None,brick,standard,1.0,NaN,0.35,37.495419,55.819282,6.00
7,1.950697e+09,Москва,"улица Габричевского, 10к2",11500000.0,36.4,1.0,8.0,14.0,None,brick,standard,1.0,NaN,0.96,37.461032,55.816101,7.28
8,2.059491e+09,Москва,"улица Менжинского, 21",13000000.0,41.1,1.0,6.0,12.0,None,brick,standard,1.0,NaN,0.35,37.667438,55.868849,8.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30436,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,None,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,27.00
30437,1.525961e+09,Санкт-Петербург,"Морской проспект, 33",98900000.0,241.8,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.39,30.260754,59.971713,48.36
30438,2.059036e+09,Санкт-Петербург,"Ушаковская набережная, 3 к2",85000000.0,156.0,4.0,13.0,17.0,None,brick_monolith,design,2.0,Чёрная речка,1.07,30.315220,59.982272,31.20
30439,1.633886e+09,Санкт-Петербург,"Кемская улица, 14",66500000.0,124.7,4.0,2.0,7.0,None,brick_monolith,design,2.0,Крестовский остров,0.49,30.263047,59.973401,24.94
30440,2.056289e+09,Санкт-Петербург,"Парадная улица, 3к2",79000000.0,153.0,4.0,6.0,8.0,None,brick_monolith,well_done,2.0,Площадь Восстания,1.75,30.367261,59.942079,30.60

In [134]:
dk_df2 = pd.merge(dk_df, years, how="left", on=["uid"]).drop_duplicates()

In [137]:
dk_df2["build_date"] = dk_df2["year"]

In [140]:
dk_df2.drop("year", axis=1, inplace=True)

In [141]:
dk_df2

,uid,city,address,price,area,total_rooms,floor,total_floors,build_date,material_type,remont,total_balcony,metro_name,metro_dist_km,longitude,latitude,kitchen_area
0,2.056866e+09,Москва,"Выборгская улица, 8",10680000.0,35.0,1.0,1.0,9.0,1965.0,brick,standard,1.0,NaN,0.78,37.490110,55.833107,7.00
2,2.058753e+09,Москва,"улица Гурьянова, 9",12990000.0,40.5,1.0,3.0,12.0,1978.0,brick,standard,1.0,NaN,0.66,37.721660,55.690146,8.10
4,2.056577e+09,Москва,"Ленинградское шоссе, 13к2",10400000.0,30.0,1.0,5.0,5.0,1960.0,brick,standard,1.0,NaN,0.35,37.495419,55.819282,6.00
6,2.060026e+09,Москва,"Звенигородское шоссе, 3Ас1",12900000.0,32.0,1.0,3.0,9.0,NaN,brick,standard,1.0,NaN,0.42,37.556559,55.763523,6.40
7,2.060013e+09,Москва,"Большая Черкизовская улица, 26к2",10300000.0,31.7,1.0,5.0,5.0,NaN,brick,standard,1.0,NaN,0.96,37.737740,55.797766,6.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47662,2.059546e+09,Санкт-Петербург,"улица Червонного Казачества, 26",6500000.0,48.5,4.0,1.0,5.0,1960.0,panel,standard,1.0,Автово,0.91,30.272776,59.865379,9.70
47720,2.059449e+09,Санкт-Петербург,"Свердловская набережная, 58",73000000.0,154.4,4.0,11.0,14.0,2014.0,brick_monolith,design,1.0,NaN,NaN,30.406760,59.956183,30.88
47727,1.979478e+09,Санкт-Петербург,"улица Брянцева, 13к1",30000000.0,110.0,4.0,25.0,25.0,2012.0,brick_monolith,well_done,1.0,Гражданский проспект,1.14,30.407505,60.039768,22.00
47734,1.912572e+09,Санкт-Петербург,"9-я Советская улица, 5",69500000.0,221.6,4.0,7.0,8.0,2006.0,brick_monolith,well_done,1.0,Площадь Восстания,1.37,30.371950,59.938189,44.32
47737,1.870651e+09,Санкт-Петербург,"проспект Непокорённых, 49к2",20500000.0,135.0,4.0,7.0,16.0,2010.0,brick_monolith,design,2.0,Площадь Мужества,1.86,30.389054,59.993599,27.00

In [145]:
rdf = pd.concat([cian_df, dk_df2])

In [147]:
rdf.to_csv("result_df.csv", index=False)